name: Question
description: Ask a question about something CCXT related
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        ## If you want your question to be answered quickly, we strongly recommend that you

        - Read the [Manual](https://github.com/ccxt/ccxt/wiki/Manual), and give special attention to the following sections:
          - [Exchange Properties](https://github.com/ccxt/ccxt/wiki/Manual#exchange-properties)
          - [Rate Limit](https://github.com/ccxt/ccxt/wiki/Manual#rate-limit)
          - [DDoS Protection](https://github.com/ccxt/ccxt/wiki/Manual#ddos-protection-by-cloudflare--incapsula)
          - [Authentication](https://github.com/ccxt/ccxt/wiki/Manual#authentication)
          - [API Keys Setup](https://github.com/ccxt/ccxt/wiki/Manual#api-keys-setup)
        - Read the [API docs](https://github.com/ccxt/ccxt/wiki/Exchange-Markets) for your exchange.
        
        ------------------

        ## Preliminary Checks

        ### By posting an issue using this template, you agree that

        - You have already searched for [existing issues](https://github.com/ccxt/ccxt/issues) and confirmed that this issue is not a duplicate
        - This question is directly related to ccxt
        - You have read the [FAQ](https://github.com/ccxt/ccxt/wiki/FAQ) for most frequently asked questions
        - This is not a bug report ([please select Bug Report instead of Question to report a bug](https://github.com/samgermain/ccxt-clone/issues/new/choose))

  - type: input
    id: operating-system
    attributes:
      label: Operating System
      placeholder: "e.g. MacOS Monteray v12.5.1 Intel Core i3"
      description: |
        - `uname -mpovr`                                                       (Linux) 
        - selecting ** -> System Preferences -> Overview** from the menu bar  (MacOs)
        - #TODO                                                                (Windows)
    validations:
      required: true
  - type: input
    id: language-version
    attributes:
      label: Language and Version
      placeholder: "e.g. Node v18.4.0"
      description: |
        - `node -v`   (JavaScript)
        - `python -V` (Python)
        - `php -v`    (PHP)
    validations:
      required: true
  - type: input
    id: ccxt-version
    attributes:
      label: CCXT Version
      placeholder: "e.g. v18.4.0"
      description: |
        - `npm info ccxt version`         (JavaScript)
        - `pip freeze | grep ccxt`        (Python)
        - `php --ri ccxt | grep Version`  (PHP)
    validations:
      required: true

  - type: textarea
    attributes:
      label: Description
      description: Describe the question that you have using words. Be precise. Include clear steps for how to reproduce any issues
      value: |
        1.
        2.
        3.
        ...
    validations:
      required: true

  - type: textarea
    attributes:
      label: Code
      description: If your question is about your code, please post a complete program containing the minimal amount of code required, so that we can copy and paste your code and receive the same error. DON'T POST SCREENSHOTS OF CODE OR ERRORS, POST THE OUTPUT AND CODE IN PLAIN TEXT!
      placeholder: |
        paste your code here, between triple backticks(```), in the format of
          ```[your_programming_language]
          REPLACE_THIS_WITH_YOUR_OUTPUT_IN_TEXT_NO_SCREENSHOTS
          ```
        e.g. 
          ```js
          let x = 0;
          console.log (x);
          ```
    validations:
      required: false

  - type: textarea
    attributes:
      label: Current Result
      description: If your question is about your code, please paste the **full verbose output** (with `exchange.verbose = true`, should include the request and response from the exchange (not just an error callstack)). Remember to remove your apiKey, secret, password, etc.
      placeholder: |
        paste your code here, between triple backticks(```), in the format of
          ```[your_programming_language]
          REPLACE_THIS_WITH_YOUR_OUTPUT_IN_TEXT_NO_SCREENSHOTS
          ```
        e.g. 
          ```js
          let x = 0;
          console.log (x);
          ```
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        ### Please make sure you have removed you `apiKey` and `secret` from the output posted above under **Current Result** and **Code**

  - type: textarea
    attributes:
      label: Expected Result
      description: If the output posted above is different than the desired output, please post the desired output here
      placeholder: |
        paste your code here, between triple backticks(```), in the format of
          ```[your_programming_language]
          REPLACE_THIS_WITH_YOUR_OUTPUT_IN_TEXT_NO_SCREENSHOTS
          ```
        e.g. 
          ```js
          let x = 0;
          console.log (x);
          ```
    validations:
      required: false
  